### ISSUE TITLE
Bug when selecting a different spectrum image if there is already one selected.

### ISSUE THREAD

**Issue by Xx-Ashutosh-xX** [Blackcipher101/Spaceye#11]
The new selection doesn't overwrite the previous spectrum image selection. 
which further can't display the colour graph of the new one and is stuck on previous selection.

**Comment by Blackcipher101** [comment]
@Xx-Ashutosh-xX Will, you be working on it.

**Comment by Xx-Ashutosh-xX** [comment]
> @Xx-Ashutosh-xX Will, you be working on it.

Sure, let me just understand the codebase then I will work on it.
