### ISSUE TITLE
Remove all .py files expect main.py

### ISSUE THREAD

**Issue by Blackcipher101** [Blackcipher101/Spaceye#8]
all .py files are rendered useless as the code has already been moved to main.py

**Comment by NirvikC** [comment]
I want to start with this since I am completely new to open source

**Comment by Blackcipher101** [comment]
you can first try https://github.com/Blackcipher101/Spaceye/issues/9

**Comment by hey-amanthakur** [comment]
![image](https://user-images.githubusercontent.com/54764701/101440278-688faf00-393c-11eb-9bb9-6676e3c54f98.png)

**Comment by Blackcipher101** [comment]
@jhonsnow456 make sure you comment that you working on it
